### PR TITLE
fix(prototyper): validate DBCN console shared memory range

### LINKED ISSUE #192: [BUG] prototyper: DBCN console_write hangs on invalid physical buffer instead of returning invalid_param
## Summary

`SBI_EXT_DBCN_CONSOLE_WRITE` (`eid = 0x4442434E`, `fid = 0x0`) hangs RustSBI Prototyper when given an invalid physical buffer address, instead of returning `invalid_param`.

The minimized reproducer is:

- `len = 0x24`
- `phys_addr_lo = 0x2`
- `phys_addr_hi = 0x0`

## Expected behavior

The `Console::write` contract says invalid memory should return `SbiRet::invalid_param()`, not hang.

## Actual behavior

RustSBI Prototyper prints the normal startup banner and then hangs indefinitely until killed by `timeout`.

### 1. Clone and build RustSBI Prototyper

```bash
git clone https://github.com/rustsbi/rustsbi.git
cd rustsbi

cargo install cargo-binutils
cargo xtask prototyper
```

This should produce:

```bash
target/riscv64imac-unknown-none-elf/release/rustsbi-prototyper.bin
```

### 2. Build a tiny S-mode payload that performs the invalid `console_write`

Create `/tmp/rustsbi_issue_repro.c`:

```c
#include <stdint.h>

struct sbiret {
    long error;
    long value;
};

static inline struct sbiret sbi_dbcn_console_write(uint64_t len, uint64_t addr_lo, uint64_t addr_hi) {
    register uint64_t a0 asm("a0") = len;
    register uint64_t a1 asm("a1") = addr_lo;
    register uint64_t a2 asm("a2") = addr_hi;
    register uint64_t a6 asm("a6") = 0;
    register uint64_t a7 asm("a7") = 0x4442434EULL;
    asm volatile ("ecall" : "+r"(a0), "+r"(a1) : "r"(a2), "r"(a6), "r"(a7) : "memory", "a3", "a4", "a5");
    return (struct sbiret){ .error = (long)a0, .value = (long)a1 };
}

void _start(void) {
    (void)sbi_dbcn_console_write(0x24, 0x2, 0x0);
    for (;;) {
        asm volatile ("wfi");
    }
}
```

Create `/tmp/rustsbi_issue_repro.ld`:

```ld
OUTPUT_ARCH(riscv)
ENTRY(_start)
SECTIONS {
  . = 0x80600000;
  .text : { *(.text .text.*) }
  .rodata : { *(.rodata .rodata.*) }
  .data : { *(.data .data.*) }
  .bss : { *(.bss .bss.* COMMON) }
}
```

Build it:

```bash
riscv64-unknown-elf-gcc \
  -nostdlib \
  -static \
  -march=rv64imac \
  -mabi=lp64 \
  -T /tmp/rustsbi_issue_repro.ld \
  -o /tmp/rustsbi_issue_repro.elf \
  /tmp/rustsbi_issue_repro.c
```

### 3. Run plain QEMU

```bash
timeout 12s qemu-system-riscv64 \
  -M virt \
  -m 256M \
  -smp 4 \
  -bios target/riscv64imac-unknown-none-elf/release/rustsbi-prototyper.bin \
  -kernel /tmp/rustsbi_issue_repro.elf \
  -monitor null \
  -serial stdio \
  -nographic \
  -snapshot
echo $?
```

### 4. Observed result

Expected if the bug is present:

- RustSBI prints the normal startup banner
- it never returns / never reports an SBI error
- QEMU hangs until killed by `timeout`
- shell exit code is `124`

## Why this looks like a real bug

The reproducer is already minimized to a single call:

```text
console_write(len=0x24, phys_addr_lo=0x2, phys_addr_hi=0x0)
```

## Suspected root cause

In Prototyper, the debug console implementation converts the physical address directly into a raw slice without validating the range first:

```rust
fn write(&self, bytes: Physical<&[u8]>) -> SbiRet {
    // TODO: verify valid memory range for a `Physical` slice.
    let start = bytes.phys_addr_lo();
    let buf = unsafe { core::slice::from_raw_parts(start as *const u8, bytes.num_bytes()) };
    let bytes_written = self.inner.lock().write(buf);
    SbiRet::success(bytes_written)
}
```

So an obviously invalid address like `0x2` is not rejected and instead drives the firmware into a stable hang path.

## Suggested fix

Validate the physical range before `from_raw_parts` and return `SbiRet::invalid_param()` when the DBCN buffer is not a valid accessible supervisor-shared memory region.

### PR DESCRIPTION
**Pull request by manchangfengxu**
SBI DBCN console_write/console_read previously converted the physical buffer into a raw slice without validating its physical address range. Passing an invalid buffer (e.g. addr=0x2, len=0x24) could therefore hang Prototyper instead of returning invalid_param, violating the Console::write/read contract.

Validate the `[start, start + len)` range against the platform DRAM `memory_range` before creating the raw slice, and return SbiRet::invalid_param() on invalid ranges. Also compose the full physical address from hi/lo parts.

Fix: #192
## What
Fixed a potential firmware hang in the Prototyper's DBCN implementation when 
provided with invalid physical memory buffers.

## Why
Directly converting an unverified supervisor-provided physical address (e.g., 
addr=0x2) into a Rust slice and accessing it in M-mode triggers hardware 
exceptions or stable hangs. This violates the SBI Console contract, which 
requires returning `invalid_param` for inaccessible memory.

## How
- Compose the full 64-bit physical address from `phys_addr_hi` and `phys_addr_lo`.
- Implement a check to validate the `[start, start + len)` range against the 
  platform's DRAM `memory_range`.
- Use `checked_add` to safely calculate the end address and prevent overflow.
- Return `SbiRet::invalid_param()` if the range is invalid or inaccessible.
## Testing
Verified using a custom S-mode C payload on QEMU Virt machine.
#### Observed Output:

``` Plaintext
[RustSBI] INFO  - Boot HART MHPM Mask:          : 0x07ffff
[RustSBI] INFO  - The patched dtb is located at 0x8005c000 with length 0x1eb0.
[RustSBI] INFO  - Redirecting hart 0 to 0x00000080600000 in Supervisor mode.
ANY0
```
(Note: 'A' = Payload start, 'N' = Invalid addr check passed, 'Y' = Valid addr check passed, '0' = QEMU Exit 0)
Test Setup:

Payload linked at 0x80600000.

Manually initialized sp to 0x90000000 (DRAM end).

Case 1 (Invalid Write): Call console_write with addr=0x2. Expected: Returns -2 (invalid_param). Observed: Prints 'N' and continues.

Case 2 (Valid Read): Call console_read with addr=0x80700000. Expected: Returns 0 (success). Observed: Prints 'Y'.

Exit: System shuts down via SRST to confirm completion.

<details>
<summary>点击查看测试 Payload 代码 (C)</summary>

``` c
#include <stdint.h>

struct sbiret {
    long error;
    long value;
};

// Legacy putchar for markers
static inline void console_putchar(uint64_t ch) {
    register uint64_t a0 asm("a0") = ch;
    register uint64_t a7 asm("a7") = 1; 
    asm volatile ("ecall" : "+r"(a0) : "r"(a7) : "memory", "a1", "a2", "a3", "a4", "a5", "a6");
}

static inline struct sbiret sbi_dbcn_console_write(uint64_t len, uint64_t addr_lo, uint64_t addr_hi) {
    register uint64_t a0 asm("a0") = len;
    register uint64_t a1 asm("a1") = addr_lo;
    register uint64_t a2 asm("a2") = addr_hi;
    register uint64_t a6 asm("a6") = 0; 
    register uint64_t a7 asm("a7") = 0x4442434EULL; 
    asm volatile ("ecall" : "+r"(a0), "+r"(a1), "+r"(a2), "+r"(a6), "+r"(a7) : : "memory", "a3", "a4", "a5");
    return (struct sbiret){ .error = (long)a0, .value = (long)a1 };
}

static inline struct sbiret sbi_dbcn_console_read(uint64_t len, uint64_t addr_lo, uint64_t addr_hi) {
    register uint64_t a0 asm("a0") = len;
    register uint64_t a1 asm("a1") = addr_lo;
    register uint64_t a2 asm("a2") = addr_hi;
    register uint64_t a6 asm("a6") = 1; 
    register uint64_t a7 asm("a7") = 0x4442434EULL; 
    asm volatile ("ecall" : "+r"(a0), "+r"(a1), "+r"(a2), "+r"(a6), "+r"(a7) : : "memory", "a3", "a4", "a5");
    return (struct sbiret){ .error = (long)a0, .value = (long)a1 };
}

static inline void shutdown(void) {
    register uint64_t a0 asm("a0") = 0;
    register uint64_t a1 asm("a1") = 0;
    register uint64_t a6 asm("a6") = 0;
    register uint64_t a7 asm("a7") = 0x53525354ULL; 
    asm volatile ("ecall" : "+r"(a0), "+r"(a1), "+r"(a6), "+r"(a7) : : "memory", "a2", "a3", "a4", "a5");
    for (;;) { asm volatile ("wfi"); }
}

static void payload_main(void) {
    console_putchar('A'); // Start marker

    // Test invalid address
    struct sbiret w = sbi_dbcn_console_write(0x24, 0x2, 0x0);
    console_putchar(w.error == 0 ? 'Y' : 'N'); // Expected 'N'

    // Test valid address
    struct sbiret r = sbi_dbcn_console_read(0x24, 0x80700000, 0x0);
    console_putchar(r.error == 0 ? 'Y' : 'N'); // Expected 'Y'

    shutdown();
}

__attribute__((naked, noreturn, section(".text.entry"), aligned(4))) void _start(void) {
    asm volatile(
        "li sp, 0x90000000\n"
        "j payload_main\n"
    );
    __builtin_unreachable();
}
```
<details>
<summary>📝 <strong>Click for commit rules checklist / 点击查看提交规范检查表</strong></summary>

- [Commit Rules (EN)](https://github.com/rustsbi/slides/blob/main/2025/reports/Contributing%20to%20RustSBI.md)
- [Commit Rules (ZH)](https://github.com/rustsbi/slides/blob/main/2025/reports/%E4%B8%BA%20RustSBI%20%E8%B4%A1%E7%8C%AE.md)

</details>

### CODE REVIEW

File: prototyper/prototyper/src/sbi/console.rs [hunk 1]
```diff
@@ -5,6 +5,31 @@ use spin::Mutex;
 
 use crate::platform::PLATFORM;
 
+// Compose a full physical address from the low/high 32-bit parts.
```
Comment (Plucky923) [inline prototyper/prototyper/src/sbi/console.rs]: The first line should follow the doc comment convention: third-person singular present indicative and one concise sentence.
Compose ... is imperative; consider rewriting it as Returns ....
Also, if this is intended as API documentation, it should use /// instead of //.
